# Generated by Django 4.1.7 on 2023-07-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
    ]
